# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dmlf.communication import cml_pb2 as dmlf_dot_communication_dot_cml__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dmlf/communication/cml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterManagerStub:
    """Define the Cluster Management Layer (CML) service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/cml.ClusterManager/RegisterNode',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/cml.ClusterManager/SendHeartbeat',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ListenForCommands = channel.unary_stream(
                '/cml.ClusterManager/ListenForCommands',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.CommandListenRequest.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.Command.FromString,
                _registered_method=True)
        self.ReportJobStatus = channel.unary_unary(
                '/cml.ClusterManager/ReportJobStatus',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/cml.ClusterManager/SubmitJob',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.JobSubmitRequest.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.JobSubmitResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/cml.ClusterManager/StreamLogs',
                request_serializer=dmlf_dot_communication_dot_cml__pb2.LogMessage.SerializeToString,
                response_deserializer=dmlf_dot_communication_dot_cml__pb2.LogAck.FromString,
                _registered_method=True)


class ClusterManagerServicer:
    """Define the Cluster Management Layer (CML) service
    """

    def RegisterNode(self, request, context):
        """Agent registers itself to the Manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Agent sends a periodic heartbeat with hardware metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenForCommands(self, request, context):
        """Manager streams commands (like LaunchJob, StopJob) down to the Agent
        This uses a server-side stream so the agent can keep a connection open
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJobStatus(self, request, context):
        """Agent reports back the status of a job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """User CLI submits a new job to the cluster manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Agent streams structured logs back to the Manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.RegistrationRequest.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.RegistrationResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.HeartbeatRequest.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ListenForCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenForCommands,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.CommandListenRequest.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.Command.SerializeToString,
            ),
            'ReportJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJobStatus,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.JobStatusRequest.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.JobStatusResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.JobSubmitRequest.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.JobSubmitResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=dmlf_dot_communication_dot_cml__pb2.LogMessage.FromString,
                    response_serializer=dmlf_dot_communication_dot_cml__pb2.LogAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cml.ClusterManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cml.ClusterManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterManager:
    """Define the Cluster Management Layer (CML) service
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cml.ClusterManager/RegisterNode',
            dmlf_dot_communication_dot_cml__pb2.RegistrationRequest.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cml.ClusterManager/SendHeartbeat',
            dmlf_dot_communication_dot_cml__pb2.HeartbeatRequest.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenForCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cml.ClusterManager/ListenForCommands',
            dmlf_dot_communication_dot_cml__pb2.CommandListenRequest.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cml.ClusterManager/ReportJobStatus',
            dmlf_dot_communication_dot_cml__pb2.JobStatusRequest.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cml.ClusterManager/SubmitJob',
            dmlf_dot_communication_dot_cml__pb2.JobSubmitRequest.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.JobSubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cml.ClusterManager/StreamLogs',
            dmlf_dot_communication_dot_cml__pb2.LogMessage.SerializeToString,
            dmlf_dot_communication_dot_cml__pb2.LogAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
