apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "dmlf.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth_token: {{ .Values.global.authToken | quote }}